language: php

sudo: false

php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer require php-coveralls/php-coveralls:^1.0
  - travis_retry composer update --no-interaction --dev

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpunit

after_success:
  - php vendor/bin/coveralls -v
  - php vendor/bin/codacycoverage clover build/logs/clover.xml